name: Weekly Update
 
on:
schedule:
 
- cron: '0 1 * * 1'
 
jobs:
build:
runs-on: ubuntu-latest
 
steps:
 
- uses: actions/checkout@v3
- name: Set up Python
uses: actions/setup-python@v4
with:
  python-version: '3.x'
- name: Generate summary
run: python update_summary.py
- name: Commit & push
run: git config --local user.email "hzr00000sz@qq.com"
- run: git config --local user.name "yfyyyyfyhsb-dotcom"
- run: git add weekly_summary.html
- run: git commit -m "自动更新本周总结"
- run: git push
